import type { ConversionGoal, Campaign } from "./types"

// Helper function to generate realistic trend data
function generateTrendData(baseValue: number, volatility: number, trend: number, points = 12): number[] {
  const data: number[] = []
  let currentValue = baseValue - (baseValue * trend * points) / 200 // Start lower/higher based on trend

  for (let i = 0; i < points; i++) {
    // Add some randomness but follow the overall trend
    const randomFactor = (Math.random() - 0.5) * volatility
    currentValue = currentValue * (1 + trend / 100 / points + randomFactor)
    data.push(Math.round(currentValue))
  }

  return data
}

export const conversionGoals: ConversionGoal[] = [
  // Acquisition metrics
  {
    id: "goal1",
    name: "Website Visitors",
    description: "Count of unique visitors to the website in the last 30 days",
    category: "acquisition",
    value: 25000,
    conversions: 25000,
    target: 30000,
    campaigns: 6,
    trend: 15.7,
    trendData: generateTrendData(20000, 0.1, 15.7, 12),
    metricType: "outcome",
  },
  {
    id: "goal2",
    name: "Ad Clicks",
    description: "Number of clicks on paid advertisements in the last 30 days",
    category: "acquisition",
    value: 35000,
    conversions: 35000,
    target: 40000,
    campaigns: 4,
    trend: -5.2,
    trendData: generateTrendData(38000, 0.08, -5.2, 12),
  },
  {
    id: "goal3",
    name: "First Page View to Signup",
    description: "Users who sign up within 5 minutes of first page view",
    category: "acquisition",
    value: 18000,
    conversions: 1800,
    target: 2000,
    campaigns: 3,
    trend: 8.5,
    trendData: generateTrendData(1500, 0.07, 8.5, 12),
    metricType: "aha",
  },
  {
    id: "goal4",
    name: "Referral Program Signups",
    description: "Number of new users who sign up through referrals",
    category: "acquisition",
    value: 42000,
    conversions: 840,
    target: 1000,
    campaigns: 2,
    trend: 12.3,
    trendData: generateTrendData(700, 0.09, 12.3, 12),
  },

  // Activation metrics
  {
    id: "goal5",
    name: "Free Trial Starts",
    description: "Number of users who start a free trial",
    category: "activation",
    value: 99000,
    conversions: 9900,
    target: 12000,
    campaigns: 5,
    trend: 12.5,
    trendData: generateTrendData(8500, 0.05, 12.5, 12),
    metricType: "outcome",
  },
  {
    id: "goal6",
    name: "First Value Moment",
    description: "Users who complete their first project within 24 hours",
    category: "activation",
    value: 15000,
    conversions: 1500,
    target: 2000,
    campaigns: 3,
    trend: 5.2,
    trendData: generateTrendData(1200, 0.06, 5.2, 12),
    metricType: "aha",
  },
  {
    id: "goal7",
    name: "Onboarding Steps Completed",
    description: "Total number of onboarding steps completed by all users",
    category: "activation",
    value: 32000,
    conversions: 32000,
    target: 40000,
    campaigns: 3,
    trend: 7.5,
    trendData: generateTrendData(28000, 0.04, 7.5, 12),
  },

  // Engagement metrics
  {
    id: "goal8",
    name: "Daily Active Users (DAU)",
    description: "Number of unique users who engage with the product daily",
    category: "engagement",
    value: 45000,
    conversions: 4500,
    target: 5000,
    campaigns: 4,
    trend: 6.3,
    trendData: generateTrendData(4000, 0.03, 6.3, 12),
  },
  {
    id: "goal9",
    name: "Feature Discovery",
    description: "Users who discover and use at least 3 core features",
    category: "engagement",
    value: 22000,
    conversions: 2200,
    target: 2500,
    campaigns: 3,
    trend: 4.7,
    trendData: generateTrendData(1800, 0.05, 4.7, 12),
    metricType: "aha",
  },
  {
    id: "goal10",
    name: "Total Session Count",
    description: "Total number of user sessions in the last 30 days",
    category: "engagement",
    value: 38000,
    conversions: 38000,
    target: 42000,
    campaigns: 2,
    trend: 3.2,
    trendData: generateTrendData(32000, 0.04, 3.2, 12),
  },

  // Monetization metrics
  {
    id: "goal11",
    name: "Paid Subscriptions",
    description: "Number of paid subscriptions activated",
    category: "monetization",
    value: 85000,
    conversions: 8500,
    target: 10000,
    campaigns: 5,
    trend: 9.2,
    trendData: generateTrendData(7000, 0.06, 9.2, 12),
    metricType: "outcome",
  },
  {
    id: "goal12",
    name: "First Upgrade Decision",
    description: "Users who view the pricing page within first week",
    category: "monetization",
    value: 28000,
    conversions: 2800,
    target: 3500,
    campaigns: 2,
    trend: 6.8,
    trendData: generateTrendData(2400, 0.05, 6.8, 12),
    metricType: "aha",
  },
  {
    id: "goal13",
    name: "Total Revenue",
    description: "Total revenue generated in the last 30 days",
    category: "monetization",
    value: 65000,
    conversions: 65000,
    target: 70000,
    campaigns: 4,
    trend: 5.8,
    trendData: generateTrendData(55000, 0.04, 5.8, 12),
    metricType: "outcome",
  },
  {
    id: "goal14",
    name: "New Paid Customers",
    description: "Number of new paid customers in the last 30 days",
    category: "monetization",
    value: 55000,
    conversions: 5500,
    target: 6000,
    campaigns: 3,
    trend: 7.4,
    trendData: generateTrendData(4500, 0.05, 7.4, 12),
  },
  {
    id: "goal15",
    name: "Product Qualified Leads",
    description: "Number of users who qualify as PQLs based on product usage",
    category: "monetization",
    value: 72000,
    conversions: 7200,
    target: 8000,
    campaigns: 4,
    trend: 8.9,
    trendData: generateTrendData(6000, 0.07, 8.9, 12),
  },

  // Retention metrics
  {
    id: "goal16",
    name: "Active Subscribers",
    description: "Number of active subscribers in the current month",
    category: "retention",
    value: 74250,
    conversions: 4950,
    target: 6000,
    campaigns: 4,
    trend: -2.1,
    trendData: generateTrendData(5100, 0.04, -2.1, 12),
    metricType: "outcome",
  },
  {
    id: "goal17",
    name: "Second Month Renewal",
    description: "Users who renew their subscription after the first month",
    category: "retention",
    value: 48000,
    conversions: 4800,
    target: 5500,
    campaigns: 3,
    trend: 5.3,
    trendData: generateTrendData(4000, 0.04, 5.3, 12),
    metricType: "aha",
  },
  {
    id: "goal18",
    name: "30-Day Active Users",
    description: "Number of users active in the last 30 days",
    category: "retention",
    value: 68000,
    conversions: 6800,
    target: 7500,
    campaigns: 5,
    trend: 3.6,
    trendData: generateTrendData(5800, 0.03, 3.6, 12),
  },
  {
    id: "goal19",
    name: "Subscription Cancellations",
    description: "Number of subscription cancellations in the last 30 days",
    category: "retention",
    value: 58000,
    conversions: 580,
    target: 500,
    campaigns: 4,
    trend: -4.2,
    trendData: generateTrendData(620, 0.05, -4.2, 12),
  },

  // Expansion metrics
  {
    id: "goal20",
    name: "Basic to Premium Upgrade",
    description: "Existing customers who upgrade from basic to premium plan",
    category: "expansion",
    value: 49500,
    conversions: 330,
    target: 500,
    campaigns: 3,
    trend: 8.3,
    trendData: generateTrendData(250, 0.08, 8.3, 12),
    metricType: "outcome",
  },
  {
    id: "goal21",
    name: "First Add-On Purchase",
    description: "Users who purchase their first add-on or extension",
    category: "expansion",
    value: 32000,
    conversions: 3200,
    target: 4000,
    campaigns: 2,
    trend: 7.5,
    trendData: generateTrendData(2800, 0.06, 7.5, 12),
    metricType: "aha",
  },
  {
    id: "goal22",
    name: "Additional Seats Purchased",
    description: "Number of additional seats purchased by existing customers",
    category: "expansion",
    value: 82000,
    conversions: 820,
    target: 900,
    campaigns: 4,
    trend: 6.7,
    trendData: generateTrendData(700, 0.04, 6.7, 12),
    metricType: "outcome",
  },
  {
    id: "goal23",
    name: "Expansion MRR",
    description: "Additional monthly recurring revenue from existing customers",
    category: "expansion",
    value: 63000,
    conversions: 630,
    target: 700,
    campaigns: 3,
    trend: 9.4,
    trendData: generateTrendData(550, 0.06, 9.4, 12),
  },
  {
    id: "goal24",
    name: "Annual Plan Conversion",
    description: "Monthly subscribers who switch to annual billing",
    category: "expansion",
    value: 36000,
    conversions: 240,
    target: 300,
    campaigns: 2,
    trend: 9.8,
    trendData: generateTrendData(180, 0.07, 9.8, 12),
  },
  {
    id: "goal25",
    name: "Seats Per Account Growth",
    description: "Increase in the average number of seats per account",
    category: "expansion",
    value: 42000,
    conversions: 420,
    target: 500,
    campaigns: 2,
    trend: 7.8,
    trendData: generateTrendData(350, 0.05, 7.8, 12),
  },
]

export const campaigns: Campaign[] = [
  {
    id: "camp1",
    name: "Welcome Series",
    status: "active",
    channel: "email",
    audience: "New Signups",
    created: "2023-05-15",
    modified: "2023-06-02",
    goalIds: ["goal1", "goal4", "goal5"],
    conversions: 450,
    value: 44550,
    metrics: {
      sent: 10000,
      opened: 4500,
      clicked: 2200,
    },
  },
  {
    id: "camp2",
    name: "Trial Ending Reminder",
    status: "active",
    channel: "email",
    audience: "Trial Users (Day 12-14)",
    created: "2023-04-20",
    modified: "2023-05-18",
    goalIds: ["goal1"],
    conversions: 320,
    value: 31680,
    metrics: {
      sent: 5000,
      opened: 3200,
      clicked: 1800,
    },
  },
  {
    id: "camp3",
    name: "Premium Features Showcase",
    status: "active",
    channel: "in-app",
    audience: "Basic Plan Users (>30 days)",
    created: "2023-03-10",
    modified: "2023-04-05",
    goalIds: ["goal2"],
    conversions: 180,
    value: 27000,
    metrics: {
      sent: 8000,
      opened: 6400,
      clicked: 2100,
    },
  },
  {
    id: "camp4",
    name: "Renewal Discount Offer",
    status: "active",
    channel: "email",
    audience: "Expiring Subscriptions (7 days)",
    created: "2023-02-28",
    modified: "2023-03-15",
    goalIds: ["goal3"],
    conversions: 210,
    value: 31500,
    metrics: {
      sent: 3000,
      opened: 1800,
      clicked: 900,
    },
  },
  {
    id: "camp5",
    name: "Feature Tutorial Series",
    status: "active",
    channel: "email",
    audience: "New Users (<14 days)",
    created: "2023-06-01",
    modified: "2023-06-01",
    goalIds: ["goal5"],
    conversions: 580,
    value: 5800,
    metrics: {
      sent: 12000,
      opened: 5400,
      clicked: 3100,
    },
  },
  {
    id: "camp6",
    name: "Annual Plan Savings",
    status: "draft",
    channel: "email",
    audience: "Monthly Subscribers (>90 days)",
    created: "2023-06-10",
    modified: "2023-06-10",
    goalIds: ["goal6"],
    conversions: 0,
    value: 0,
    metrics: {
      sent: 0,
      opened: 0,
      clicked: 0,
    },
  },
  {
    id: "camp7",
    name: "Re-engagement Campaign",
    status: "active",
    channel: "push",
    audience: "Inactive Users (>30 days)",
    created: "2023-05-05",
    modified: "2023-05-20",
    goalIds: ["goal3", "goal5"],
    conversions: 190,
    value: 28500,
    metrics: {
      sent: 15000,
      opened: 4200,
      clicked: 1100,
    },
  },
  {
    id: "camp8",
    name: "Limited Time Offer",
    status: "paused",
    channel: "sms",
    audience: "All Active Users",
    created: "2023-04-15",
    modified: "2023-05-01",
    goalIds: ["goal2", "goal6"],
    conversions: 150,
    value: 22500,
    metrics: {
      sent: 20000,
      opened: 18000,
      clicked: 3500,
    },
  },
]
